# ==============================================================================
# Project: Sales Tracking System
# Functional, modular code built for stability and error handling.
# ==============================================================================

# Core data store mapping products to their monthly sales records
sales_data = {
    "laptop": [1200, 1500, 900, 1800],
    "mouse": [300, 250, 400, 350]
}

# Set tracking distinct product categories without duplicates
product_categories = {"Electronics", "Accessories"}


def add_product():
    """Initializes a new product entry with empty records and maps its category."""
    product_name = input("Enter new product name: ").strip().lower()
    
    if not product_name:
        print("Error: Product name cannot be empty.")
        return

    if product_name in sales_data:
        print(f"Error: Product '{product_name}' already exists in the system.")
        return

    category = input(f"Enter category for '{product_name}': ").strip()
    
    sales_data[product_name] = []
    if category:
        product_categories.add(category)
        
    print(f"Success: Product '{product_name}' added under category [{category}].")


def add_monthly_sale():
    """Appends a new single month sales figure to an existing product."""
    product_name = input("Enter product name to record sales: ").strip().lower()

    if product_name not in sales_data:
        print("Error: Product not found. Please add the product first using option (1).")
        return

    try:
        sale_value = float(input(f"Enter new sales figure for {product_name}: "))
        if sale_value < 0:
            print("Error: Sales value cannot be negative.")
            return
        
        sales_data[product_name].append(sale_value)
        print(f"Success: Recorded ${sale_value:.2f} for {product_name}.")
        
    except ValueError:
        print("Input Error: Please enter a valid numeric value for sales.")


def display_sales():
    """Renders all current product records in a clean tabular view."""
    if not sales_data:
        print("System data store is currently empty.")
        return

    print("\n================ CURRENT SALES RECORDS ================")
    print(f"{'Product':<15} | {'Monthly Sales History':<40}")
    print("-" * 60)
    for product, sales in sales_data.items():
        sales_str = ", ".join([f"${val:.2f}" for val in sales]) if sales else "No sales recorded yet"
        print(f"{product:<15} | {sales_str:<40}")
    print("=========================================================\n")


def calculate_total_sales():
    """Computes total lifetime revenue generated by a chosen product."""
    product_name = input("Enter product name: ").strip().lower()

    if product_name not in sales_data:
        print("Error: Product not found.")
        return

    total = sum(sales_data[product_name])
    print(f"Total sales for '{product_name}' across all months: ${total:.2f}")


def calculate_average_sales():
    """Computes the calculated average monthly sales for a specific item."""
    product_name = input("Enter product name: ").strip().lower()

    if product_name not in sales_data:
        print("Error: Product not found.")
        return

    sales_list = sales_data[product_name]
    if not sales_list:
        print(f"Product '{product_name}' has no recorded months to average.")
        return

    avg = sum(sales_list) / len(sales_list)
    print(f"Average monthly sales for '{product_name}': ${avg:.2f}")


def find_top_product():
    """Determines the single top-grossing product inside the catalog."""
    if not sales_data:
        print("System data store is empty.")
        return

    top_product = None
    highest_revenue = -1

    for product, sales in sales_data.items():
        total_revenue = sum(sales)
        if total_revenue > highest_revenue:
            highest_revenue = total_revenue
            top_product = product

    if top_product and highest_revenue > 0:
        print(f"Top performing product: '{top_product}' with total revenue of: ${highest_revenue:.2f}")
    else:
        print("No products currently have sales history recorded.")


def main_menu():
    """Main control loop handling console interactions."""
    while True:
        print("\n" + "="*30)
        print("=== SALES TRACKER SYSTEM ===")
        print("="*30)
        print("1. Add New Product")
        print("2. Record New Monthly Sale")
        print("3. Display All Products & Sales")
        print("4. Calculate Total Product Sales")
        print("5. Calculate Average Product Sales")
        print("6. View Top Selling Product")
        print("7. Exit System")
        print("="*30)
        
        choice = input("Select an option (1-7): ").strip()

        if choice == "1":
            add_product()
        elif choice == "2":
            add_monthly_sale()
        elif choice == "3":
            display_sales()
        elif choice == "4":
            calculate_total_sales()
        elif choice == "5":
            calculate_average_sales()
        elif choice == "6":
            find_top_product()
        elif choice == "7":
            print("\nExiting system. Goodbye!")
            break
        else:
            print("Invalid option! Please select a valid number from (1-7).")


if __name__ == "__main__":
    main_menu()